# Generated by Django 3.2.5 on 2022-07-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_auto_20220711_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Point'},
        ),
    ]
